# Generated by Django 6.0.6 on 2026-07-03 19:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.UUIDField(db_index=True)),
                (
                    "generation_uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("topic", models.CharField(max_length=300)),
                ("language", models.CharField(default="English", max_length=50)),
                ("tone", models.CharField(default="Professional", max_length=100)),
                ("blog_type", models.CharField(default="Educational", max_length=100)),
                (
                    "target_audience",
                    models.CharField(default="General", max_length=100),
                ),
                ("title", models.CharField(max_length=300)),
                ("slug", models.SlugField(max_length=350, unique=True)),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=100)),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("hero", models.JSONField()),
                ("key_takeaways", models.JSONField(blank=True, default=list)),
                ("faq", models.JSONField(blank=True, default=list)),
                ("resources", models.JSONField(blank=True, null=True)),
                ("call_to_action", models.JSONField(blank=True, null=True)),
                ("conclusion", models.JSONField()),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("generating", "Generating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("generation_version", models.PositiveIntegerField(default=1)),
                ("llm_provider", models.CharField(default="gemini", max_length=50)),
                (
                    "image_provider",
                    models.CharField(default="pollinations", max_length=50),
                ),
                ("generation_time", models.FloatField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user_id"], name="blogs_blog_user_id_d2c8b1_idx"
                    ),
                    models.Index(
                        fields=["user_id", "status"],
                        name="blogs_blog_user_id_1ff624_idx",
                    ),
                    models.Index(fields=["slug"], name="blogs_blog_slug_d0bba8_idx"),
                    models.Index(
                        fields=["category"], name="blogs_blog_categor_d7bf0a_idx"
                    ),
                    models.Index(
                        fields=["processing_status"],
                        name="blogs_blog_process_a611f1_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BlogChapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("purpose", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=255)),
                ("paragraphs", models.JSONField(default=list)),
                ("bullet_points", models.JSONField(default=list)),
                ("numbered_steps", models.JSONField(default=list)),
                ("tips", models.JSONField(default=list)),
                ("warnings", models.JSONField(default=list)),
                ("notes", models.JSONField(default=list)),
                ("examples", models.JSONField(default=list)),
                ("quotes", models.JSONField(default=list)),
                ("code_examples", models.JSONField(default=list)),
                ("tables", models.JSONField(default=list)),
                ("image", models.JSONField(default=dict)),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="blogs.blog",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("blog", "order"), name="unique_blog_chapter_order"
                    )
                ],
            },
        ),
    ]
