# Generated by Django 6.0.6 on 2026-07-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="progress",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Generation progress (0-100)"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("starting", "Starting"),
                    ("generating_outline", "Generating Outline"),
                    ("generating_hero", "Generating Hero"),
                    ("generating_content", "Generating Content"),
                    ("generating_images", "Generating Images"),
                    ("generating_seo", "Generating SEO"),
                    ("saving", "Saving"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="queued",
                max_length=20,
            ),
        ),
    ]
