# Generated by Django 6.0.6 on 2026-07-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_blog_progress_alter_blog_processing_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="current_step",
            field=models.CharField(blank=True, default="Waiting...", max_length=255),
        ),
    ]
