# Generated by Django 6.0.6 on 2026-07-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_blog_current_step"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="current_step",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="progress",
        ),
        migrations.AlterField(
            model_name="blog",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("generating", "Generating"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="queued",
                max_length=20,
            ),
        ),
    ]
