# Generated by Django 6.0.6 on 2026-07-07 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0005_generationjob"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GenerationJob",
        ),
    ]
