# Generated by Django 6.0.6 on 2026-07-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0006_delete_generationjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="length",
            field=models.CharField(default="Medium", max_length=50),
        ),
    ]
