# Generated by Django 5.2.1 on 2026-07-08 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0007_blog_length"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="blog",
            name="blogs_blog_user_id_d2c8b1_idx",
        ),
        migrations.RemoveIndex(
            model_name="blog",
            name="blogs_blog_user_id_1ff624_idx",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="user_id",
        ),
    ]
