from dataclasses import dataclass


@dataclass
class GeneratedImage:
    """
    Raw image generated by an image provider.

    This object is storage-agnostic.
    """

    image_bytes: bytes

    extension: str

    mime_type: str

    prompt: str

    alt_text: str

    provider: str